"""Lua installer generator for ``resolvescript build --installable``.

The generated Lua file can be dragged into Fusion's Console or Workspace.
It shows an installer window built with Fusion's UIManager (the same UI
engine ResolveScript uses) and installs the consolidated script to the
appropriate Scripts directory.

The installer is customizable: a project can provide its own ``installer.lua.j2``
template (via ``--installer-template`` or scaffolded with ``resolvescript create``).
"""

from __future__ import annotations

import ast
import base64
import re
from pathlib import Path

from .consolidate import BuildConfig, ConsolidateError, config_from_manifest
from .errors import ResolveScriptError
from .manifest.model import Manifest

__all__ = [
    "InstallerTemplateError",
    "build_installable_lua",
    "DEFAULT_INSTALLER_TEMPLATE",
    "render_installer",
]


class InstallerTemplateError(ResolveScriptError):
    """Raised when the installer template cannot be rendered."""


#: Default Jinja2-like template for the Lua installer.
#: Uses ``@@TOKEN@@`` substitution (same convention as workflow plugin).
DEFAULT_INSTALLER_TEMPLATE = r"""--[[--
@@INSTALLER_NAME@@ @@INSTALLER_VERSION@@ - Installer
Generated by ResolveScript. Drag this file into Fusion's Console or Workspace
to install the script.

This installer uses Fusion's UIManager (bmd.UIDispatcher) to present a GUI.
@@INSTALLER_DESCRIPTION@@
--]]--

-- The consolidated Python script, base64-encoded.
local SCRIPT_B64 = [===[
@@SCRIPT_B64@@
]===]

-- Configuration (edit these to customize the installer).
local CONFIG = {
    -- The name of the script as it will appear in Resolve's menus.
    script_name = "@@SCRIPT_NAME@@",

    -- The target category in Resolve's Scripts menu:
    -- "Scripts/Comp", "Scripts/Utility", "Scripts/Tool", "Scripts/Render",
    -- or a custom path like "Scripts/MyTools".
    target_category = "@@TARGET_CATEGORY@@",

    -- Whether to overwrite an existing script with the same name.
    overwrite = @@OVERWRITE@@,

    -- Window title.
    window_title = "Install @@SCRIPT_NAME@@",

    -- Window width/height.
    window_width = 480,
    window_height = 320,
}

-- ============================================================
-- UI Construction (Fusion UIManager)
-- ============================================================

local ui = fu.UIManager
local dispatcher = bmd.UIDispatcher(ui)

-- Build the installer window.
local function build_window()
    local win = ui:VGroup{
        ID = "installer_root",
        Weight = 1.0,
        ui:VGap(10),
        ui:Label{
            ID = "title_label",
            Text = CONFIG.window_title,
            Font = ui:Font{ Family = "Sans Serif", Size = 14, Weight = "Bold" },
            Alignment = { AlignHCenter = true, AlignVCenter = true },
        },
        ui:VGap(5),
        ui:Label{
            ID = "desc_label",
            Text = [[
This will install "@@SCRIPT_NAME@@" into DaVinci Resolve's
@@TARGET_CATEGORY@@ menu.

The script will be copied to the appropriate Scripts directory
and will be available after restarting Resolve.
]],
            WordWrap = true,
            Alignment = { AlignHCenter = true, AlignTop = true },
        },
        ui:VGap(15),
        ui:HGroup{
            Weight = 0,
            ui:HGap(0, 1),
            ui:CheckBox{
                ID = "overwrite_check",
                Text = "Overwrite if already installed",
                Checked = CONFIG.overwrite,
                Events = { "Clicked" },
            },
        },
        ui:VGap(15),
        ui:HGroup{
            Weight = 0,
            ui:HGap(0, 1),
            ui:Button{
                ID = "install_btn",
                Text = "Install",
                Weight = 0.5,
                Enabled = true,
                Events = { "Clicked" },
            },
            ui:Button{
                ID = "cancel_btn",
                Text = "Cancel",
                Weight = 0.5,
                Enabled = true,
                Events = { "Clicked" },
            },
        },
        ui:VGap(10),
        ui:Label{
            ID = "status_label",
            Text = "",
            WordWrap = true,
            Alignment = { AlignHCenter = true },
        },
    }
    return win
end

-- ============================================================
-- Installation Logic
-- ============================================================

-- Get the Resolve Scripts directory for a given category.
local function get_scripts_dir(category)
    local resolve = Resolve()
    if not resolve then
        return nil, "Cannot access Resolve API from this context"
    end

    local proj = resolve:GetProjectManager():GetCurrentProject()
    if not proj then
        return nil, "No project open - cannot determine Scripts directory"
    end

    -- The Scripts directory is platform-dependent.
    -- Fusion/Resolve exposes it via the Fusion API.
    local fusion = resolve.Fusion()
    if not fusion then
        return nil, "Fusion API not available"
    end

    -- On all platforms, the user Scripts folder is:
    -- Windows: %APPDATA%\Blackmagic Design\DaVinci Resolve\Scripts\<category>
    -- macOS: ~/Library/Application Support/Blackmagic Design/DaVinci Resolve/Scripts/<category>
    -- Linux: ~/.local/share/DaVinciResolve/Scripts/<category>
    --
    -- We use Fusion's map path to resolve it.
    local scripts_path = fusion:MapPath("Scripts:" .. category)
    if not scripts_path or scripts_path == "" then
        return nil, "Could not resolve Scripts:" .. category
    end

    return scripts_path
end

-- Write the decoded script to the target directory.
local function write_script(script_path, content_b64)
    local content = b64decode(content_b64)
    local file = io.open(script_path, "wb")
    if not file then
        return false, "Cannot open " .. script_path .. " for writing"
    end
    file:write(content)
    file:close()
    return true
end

-- Base64 decode (Fusion's Lua has no built-in, so we implement it).
local b64chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local function b64decode(data)
    data = data:gsub("%s", "")  -- remove whitespace
    local out = {}
    local i = 1
    while i <= #data do
        local c1 = b64chars:find(data:sub(i, i), 1, true) - 1
        local c2 = b64chars:find(data:sub(i+1, i+1), 1, true) - 1
        local c3 = b64chars:find(data:sub(i+2, i+2), 1, true) - 1
        local c4 = b64chars:find(data:sub(i+3, i+3), 1, true) - 1
        out[#out+1] = string.char(
            bit32.bor(bit32.lshift(c1, 2), bit32.rshift(c2, 4)),
            bit32.bor(bit32.lshift(bit32.band(c2, 15), 4), bit32.rshift(c3, 2)),
            bit32.bor(bit32.lshift(bit32.band(c3, 3), 6), c4)
        )
        i = i + 4
    end
    -- Handle padding
    local result = table.concat(out)
    if data:sub(-2) == "==" then
        result = result:sub(1, -3)
    elseif data:sub(-1) == "=" then
        result = result:sub(1, -2)
    end
    return result
end

-- ============================================================
-- Event Handler
-- ============================================================

local function on_event(ev)
    if ev.ID == "install_btn" then
        local overwrite = ui:GetView("overwrite_check").Checked
        local status = ui:GetView("status_label")
        status.Text = "Installing..."
        ui:UpdateView("status_label")

        local target_dir, err = get_scripts_dir(CONFIG.target_category)
        if not target_dir then
            status.Text = "Error: " .. err
            ui:UpdateView("status_label")
            return
        end

        -- Ensure directory exists
        local lfs = require("lfs")
        local function mkdir_p(path)
            local sep = package.config:sub(1,1)
            for dir in path:gmatch("([^"..sep.."]+)"..sep.."*") do
                local sub = (sub and sub..sep or "")..dir
                lfs.mkdir(sub)
            end
        end
        mkdir_p(target_dir)

        local script_file = target_dir .. package.config:sub(1,1) .. CONFIG.script_name .. ".py"
        local file_exists = lfs.attributes(script_file, "mode") ~= nil

        if file_exists and not overwrite then
            status.Text = "Script already exists. Check 'Overwrite' to replace."
            ui:UpdateView("status_label")
            return
        end

        local ok, err = write_script(script_file, SCRIPT_B64)
        if not ok then
            status.Text = "Error writing script: " .. err
            ui:UpdateView("status_label")
            return
        end

        status.Text = "Installed to " .. script_file .. "\nRestart Resolve to see it in the menu."
        ui:UpdateView("status_label")

        -- Auto-close after a moment
        dispatcher:AddTimer(2000, function()
            dispatcher:ExitLoop()
        end)
    elseif ev.ID == "cancel_btn" or ev.ID == "installer_root" and ev.Action == "Close" then
        dispatcher:ExitLoop()
    end
end

-- ============================================================
-- Main
-- ============================================================

local win = build_window()
dispatcher:RunLoop(win)
"""

#: Token names used in the default template.
TEMPLATE_TOKENS = {
    "INSTALLER_NAME",
    "INSTALLER_VERSION",
    "INSTALLER_DESCRIPTION",
    "SCRIPT_B64",
    "SCRIPT_NAME",
    "TARGET_CATEGORY",
    "OVERWRITE",
}


def _fill(template: str, tokens: dict[str, str]) -> str:
    """Substitute ``@@TOKEN@@`` placeholders, refusing to leave any behind."""
    text = template
    for key, value in tokens.items():
        text = text.replace(f"@@{key}@@", value)
    if "@@" in text:
        near = text[text.index("@@") : text.index("@@") + 60].splitlines()[0]
        raise InstallerTemplateError(f"unsubstituted token left in installer template near: {near!r}")
    return text


def _load_template(template_path: Path | None) -> str:
    """Load the installer template from a file or return the default."""
    if template_path:
        if not template_path.is_file():
            raise InstallerTemplateError(f"installer template not found: {template_path}")
        return template_path.read_text(encoding="utf-8")
    return DEFAULT_INSTALLER_TEMPLATE


def _consolidate_to_bytes(config: BuildConfig) -> bytes:
    """Run consolidation in memory and return the script as bytes."""
    # We need to capture the output without writing to disk.
    # Replicate the consolidate logic but return the text.
    from .consolidate import (
        STDLIB_MODULES,
        _entry_candidates,
        _find_main_blocks,
        _module_is_no_comment,
        collect_python_files,
        extract_imports,
        local_file_dependencies,
        module_dotted_name,
        order_modules,
        read_module_content,
    )

    files = collect_python_files(config.package_root, config.exclude)
    if not files:
        raise ConsolidateError(f"no Python files found under {config.package_root}")

    known = {
        module_dotted_name(f, config.package_root, config.package_name): f for f in files
    }
    if config.entry:
        entry = next(
            (
                candidate
                for candidate in _entry_candidates(config.entry, config.package_root, config.package_name)
                if candidate in known
            ),
            None,
        )
        if entry is None:
            raise ConsolidateError(f"consolidate.entry '{config.entry}' is not a module in the package")
        config.entry = entry

    for file_path in files:
        try:
            tree = ast.parse(file_path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError) as exc:
            raise ConsolidateError(f"cannot parse {file_path}: {exc}") from exc
        if _find_main_blocks(tree):
            raise ConsolidateError(f"module {file_path} has a standalone 'if __name__ == \"__main__\"' block")

    names_to_deps = {
        module_dotted_name(f, config.package_root, config.package_name): local_file_dependencies(
            f, config.package_root, config.package_name, set(known)
        )
        for f in files
    }
    ordered, _cycles = order_modules(names_to_deps)

    all_imports: set[str] = set()
    all_future: set[str] = set()
    for file_path in files:
        all_imports.update(extract_imports(file_path))
        for future in re.findall(r"^from __future__ import .+$", file_path.read_text(encoding="utf-8"), flags=re.MULTILINE):
            all_future.add(future)

    output_lines: list[str] = []
    output_lines.append('"""')
    output_lines.append(f"{config.package_name} - Consolidated single-file module for DaVinci Resolve.")
    output_lines.append("")
    output_lines.append("This file is auto-generated by 'resolvescript build --installable'.")
    output_lines.append(
        "Do not edit directly - edit the source modules under "
        f"{config.package_root.as_posix()} instead."
    )
    output_lines.append('"""')
    output_lines.append("")

    if all_future:
        for future in sorted(all_future):
            output_lines.append(future)
        output_lines.append("")

    output_lines.append("# ruff: noqa: E402,F401,F403,F405")
    output_lines.append("# flake8: noqa: E402,F401,F403,F405")
    output_lines.append("")

    root = config.package_root
    bindings: set[str] = set()
    processed: list[tuple[str, str]] = []
    for mod in ordered:
        file_path = known[mod]
        no_comment = _module_is_no_comment(file_path, root, config.package_name, config.no_comment)
        content, _, binds = read_module_content(
            file_path, root, config.package_name, no_comment, known=set(known), mod_name=mod
        )
        bindings.update(binds)
        processed.append((mod, content))

    if bindings:
        output_lines.append("import sys as _rs_sys")
        output_lines.append("_rs_shared = _rs_sys.modules[__name__]")
        output_lines.extend(sorted(bindings))
        output_lines.append("")

    stdlib_imports = sorted(all_imports & STDLIB_MODULES)
    if stdlib_imports:
        output_lines.append("# Standard library imports")
        output_lines.extend(f"import {name}" for name in stdlib_imports)
        output_lines.append("")

    for mod, content in processed:
        output_lines.append(f"# ==== Module: {mod} ====")
        output_lines.append(content)
        output_lines.append("")

    text = "\n".join(output_lines).rstrip() + "\n"

    # Verify syntax
    try:
        compile(text, "<installable>", "exec")
    except SyntaxError as exc:
        raise ConsolidateError(f"consolidated output failed syntax check: {exc}") from exc

    return text.encode("utf-8")


def build_installable_lua(
    manifest: Manifest,
    project_root: Path,
    output: Path,
    installer_template: Path | None = None,
    target_category: str = "Scripts/Utility",
    overwrite: bool = True,
) -> Path:
    """Generate a Lua installer for the project.

    :param manifest: The project manifest.
    :param project_root: Root of the project (for finding the template).
    :param output: Output file path (should end in .lua).
    :param installer_template: Optional custom template path.
    :param target_category: Resolve Scripts menu category to install into.
    :param overwrite: Default overwrite behavior.
    :return: The output path.
    """
    # Build the consolidation config
    config = config_from_manifest(project_root, manifest, output_override=None)
    script_bytes = _consolidate_to_bytes(config)
    script_b64 = base64.b64encode(script_bytes).decode("ascii")

    # Determine script name from manifest or config
    script_name = manifest.name.replace(" ", "_").replace("-", "_")

    # Load and render template
    template = _load_template(installer_template)
    tokens = {
        "INSTALLER_NAME": manifest.name,
        "INSTALLER_VERSION": manifest.version,
        "INSTALLER_DESCRIPTION": manifest.description or f"Installer for {manifest.name}",
        "SCRIPT_B64": script_b64,
        "SCRIPT_NAME": script_name,
        "TARGET_CATEGORY": target_category,
        "OVERWRITE": "true" if overwrite else "false",
    }
    rendered = _fill(template, tokens)

    output.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" keeps the Lua installer LF-only on Windows; open() rather
    # than write_text because the newline parameter needs 3.10.
    with output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    return output


def render_installer(
    manifest: Manifest,
    project_root: Path,
    target_category: str = "Scripts/Utility",
    overwrite: bool = True,
    installer_template: Path | None = None,
) -> str:
    """Render the installer to a string (for --stdout or testing)."""
    config = config_from_manifest(project_root, manifest, output_override=None)
    script_bytes = _consolidate_to_bytes(config)
    script_b64 = base64.b64encode(script_bytes).decode("ascii")
    script_name = manifest.name.replace(" ", "_").replace("-", "_")

    template = _load_template(installer_template)
    tokens = {
        "INSTALLER_NAME": manifest.name,
        "INSTALLER_VERSION": manifest.version,
        "INSTALLER_DESCRIPTION": manifest.description or f"Installer for {manifest.name}",
        "SCRIPT_B64": script_b64,
        "SCRIPT_NAME": script_name,
        "TARGET_CATEGORY": target_category,
        "OVERWRITE": "true" if overwrite else "false",
    }
    return _fill(template, tokens)
