"""Declarative dict/JSON documents as a third authoring surface.

A UI does not have to be written in Python. This module round-trips a node tree
through plain dictionaries, so a screen can be described in a data file, stored
in a project, generated by another tool, or shipped as a template::

    {
      "kind": "window",
      "props": {"title": "Render"},
      "children": [
        {"kind": "column", "props": {"gap": "md", "padding": "md"},
         "children": [
           {"kind": "label", "props": {"text": "Output", "variant": "heading"}},
           {"kind": "text_field", "props": {"value": "untitled"}},
           {"kind": "button", "props": {"text": "Render", "variant": "primary"}}
         ]}
      ]
    }

    from ResolveScript.ui import from_json

    run(from_json(Path("panel.json").read_text()))

Keys are optional — a node gets a generated one. The schema is exactly the
:class:`~ResolveScript.ui.node.Node` dataclass, so a tree that came from
:func:`to_dict` and a tree that came from the Python DSL are the same object.

Callbacks
---------

JSON has no callables, so event props (``on_click`` and friends) are dropped on
the way out and can be re-attached on the way in, keyed by node key::

    data = to_dict(panel, handlers={"save": {"on_click": save}})
    same = from_dict(data, handlers={"save": {"on_click": save}})

A JSON document may also name a registered
:class:`~ResolveScript.ui.components.Component` in its ``kind``, which is how a
data file composes with hand-written Python blocks.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping, Sequence
from typing import Any

from .components import Component, get_component
from .errors import SchemaError
from .node import Node, Raw, TwoWay, raw_element
from .node import node as make_node
from .spec import all_specs

__all__ = ["to_dict", "from_dict", "to_json", "from_json", "dumps", "loads"]

#: How a Raw node is described so it can be rebuilt from data.
RAW_KIND = "raw"


def to_dict(
    source: Any,
    *,
    values: bool = True,
    handlers: Mapping[str, Mapping[str, Callable[..., Any]]] | None = None,
    skip: Sequence[str] = (),
) -> dict[str, Any]:
    """Describe a node tree as nested dictionaries.

    :param values: read reactive props and write their current value, so the
        result is plain data. Pass ``False`` to keep ``Value`` objects.
    :param handlers: ``{node_key: {event_prop: callable}}`` to include. Anything
        not listed here is dropped, because a callable is not data.
    :param skip: prop names to leave out entirely.
    """
    node_ = _as_node(source)
    handlers = handlers or {}
    skip_names = set(skip)
    spec = all_specs().get(node_.kind)
    data: dict[str, Any] = {"kind": node_.kind}
    props = _encode_props(node_.props, spec=spec, values=values, skip=skip_names)
    for key, events in handlers.items():
        if key == node_.key:
            props.update(events)
    if props:
        data["props"] = props
    if node_.key:
        data["key"] = node_.key
    if node_.children:
        data["children"] = [
            to_dict(child, values=values, handlers=handlers, skip=skip) for child in node_.children
        ]
    return data


def from_dict(
    data: Mapping[str, Any],
    *,
    handlers: Mapping[str, Mapping[str, Callable[..., Any]]] | None = None,
    strict: bool = True,
) -> Any:
    """Rebuild a node tree from :func:`to_dict` output.

    :param handlers: ``{node_key: {event_prop: callable}}`` to attach callbacks.
    :param strict: reject props a widget does not declare. Leave it on — a
        silently ignored typo is the most expensive kind of UI bug — but turn it
        off to load a document written against a newer version.

    Raises :class:`~ResolveScript.ui.errors.SchemaError` when a document is
    malformed, so a bad template fails loudly and early.
    """
    if not isinstance(data, Mapping):
        raise SchemaError(
            f"expected an object describing a node, got {type(data).__name__}"
        )
    handlers = handlers or {}

    kind = data.get("kind")
    if not isinstance(kind, str) or not kind:
        raise SchemaError(f"every node needs a string 'kind'; got {kind!r}")

    props = dict(data.get("props") or {})
    props.update(handlers.get(str(data.get("key") or ""), {}))

    if kind == RAW_KIND:
        type_name = data.get("type")
        if not isinstance(type_name, str) or not type_name:
            raise SchemaError("a raw node needs a string 'type', e.g. 'TextEdit'")
        return raw_element(type_name, props)

    children = data.get("children") or ()
    if not isinstance(children, Sequence) or isinstance(children, (str, bytes)):
        raise SchemaError(
            f"{kind}: 'children' must be a list, got {type(children).__name__}"
        )

    key = data.get("key")
    if key is not None and not isinstance(key, str):
        raise SchemaError(f"{kind}: 'key' must be a string, got {type(key).__name__}")

    if kind not in all_specs():
        component = _component_or_error(kind)
        try:
            return component(**props).to_node()
        except TypeError as exc:
            raise SchemaError(f"component {kind!r} rejected its props: {exc}") from exc

    spec = all_specs()[kind]
    unknown = sorted(
        name
        for name in props
        if name not in spec.props and not (name.startswith("on_") and spec.native_event(name))
    )
    if unknown and strict:
        raise SchemaError(
            f"{kind!r} has no prop(s) {unknown}; known props: {sorted(spec.props)}"
        )

    built = [from_dict(child, handlers=handlers, strict=strict) for child in children]
    return make_node(kind, *built, key=key, **props)


def to_json(source: Any, **kwargs: Any) -> str:
    """Serialise a node tree to a JSON string."""
    kwargs.setdefault("handlers", {})
    data = to_dict(source, **kwargs)
    return json.dumps(data, indent=2, default=_json_default)


def from_json(text: str | bytes, **kwargs: Any) -> Any:
    """Parse a JSON document (a string, or the path to one) into a node tree."""
    payload = text
    if isinstance(payload, bytes):
        payload = payload.decode("utf-8")
    try:
        data = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise SchemaError(f"invalid JSON: {exc}") from exc
    if not isinstance(data, Mapping):
        raise SchemaError("a UI document must be a JSON object with a 'kind' key")
    return from_dict(data, **kwargs)


#: ``json``-module-flavoured aliases, for code that dumps several documents.
dumps = to_json
loads = from_json


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _as_node(source: Any) -> Node:
    if isinstance(source, Node):
        return source
    if isinstance(source, Component):
        return source.to_node()
    if isinstance(source, Raw):
        raise SchemaError("a Raw node carries a callable and cannot be serialised; "
                          "describe it as {'kind': 'raw', 'type': 'TextEdit'} instead")
    if isinstance(source, Mapping):
        return from_dict(source)
    raise SchemaError(f"expected a Node, got {type(source).__name__}")


def _component_or_error(kind: str) -> type[Component]:
    try:
        return get_component(kind)
    except Exception as exc:
        widgets = sorted(all_specs())
        raise SchemaError(
            f"{kind!r} is neither a widget nor a registered component. "
            f"Widgets: {widgets}"
        ) from exc


def _encode_props(
    props: Mapping[str, Any],
    *,
    spec: Any,
    values: bool,
    skip: set[str],
) -> dict[str, Any]:
    """Serialise props, omitting anything left at its default.

    Dropping defaults keeps an exported template readable: a button that is
    merely a button serialises as ``{"text": "Go"}``, not as a page of
    ``false``/``0``/``""`` that restates the spec.
    """
    from .state import is_reactive

    out: dict[str, Any] = {}
    for name, value in props.items():
        if name in skip or name == "theme":
            continue
        if name.startswith("on_") and callable(value):
            continue
        if callable(value) or isinstance(value, Component):
            continue

        source = value.source if isinstance(value, TwoWay) else value
        # ``values=False`` keeps the live object, so a document re-attaches to
        # the same state instead of a snapshot taken at export time.
        live = is_reactive(source)
        if live and values:
            value = source.get()
        elif not live and spec is not None and _is_default(spec.props.get(name), value):
            continue

        out[name] = value if (live and not values) else _plain(value)
    return out


def _is_default(prop: Any, value: Any) -> bool:
    from .spec import UNSET

    if prop is None or prop.default is UNSET:
        return False
    if value is prop.default:
        return True
    try:
        return bool(value == prop.default)
    except Exception:  # pragma: no cover - exotic __eq__
        return False


def _plain(value: Any) -> Any:
    """Coerce a prop into something ``json.dumps`` accepts."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, TwoWay):
        return _plain(value.source)
    from .state import is_reactive

    if is_reactive(value):
        return _plain(value.get())
    if isinstance(value, Mapping):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_plain(item) for item in value]
    if hasattr(value, "to_dict"):
        return value.to_dict()
    if hasattr(value, "hex"):  # Color
        return str(value.hex)
    return str(value)


def _json_default(value: Any) -> Any:
    if isinstance(value, Node):
        return to_dict(value)
    return _plain(value)
