"""Generating the Electron Workflow Integration plugin.

A plugin is an Electron app that Resolve launches as its main process, and it
only works on Windows and macOS. Resolve reads ``manifest.xml`` at scan time to
build the menu entry, and hands the app a native Node addon,
``WorkflowIntegration.node``, which is the only way to reach Resolve's
JavaScript API — and the only way Resolve delivers callbacks.

So the two artifacts are not alternatives. The plugin is a shell: it owns the
window, owns the callbacks, and talks to the Python integration that this
project actually ships. :func:`render_plugin` writes the shell; see
:mod:`ResolveScript.workflow.script` for the brain.

The file layout matches what Resolve documents and what the shipped plugins
use::

    com.acme.deliver/
        manifest.xml        <BlackmagicDesign><Plugin> — Id, Name, Version,
                             Description, FilePath. Read at scan time.
        package.json        standard Electron app manifest, "main": "main.js"
        main.js             Electron main process: loads the native addon,
                             registers callbacks, runs the Python bridge
        preload.js          contextBridge surface for the renderer
        index.html          the page Resolve shows
        js/bridge.js        line-protocol client for the Python process
        js/app.js           the page's behaviour
        css/app.css

Substitution is done with ``@@TOKEN@@`` replacement rather than
``str.format``: these templates are JavaScript and CSS, so nearly every line
braces, and escaping them all would be one forgotten brace away from shipping
broken code. :func:`_fill` is the only place a template is interpolated.

Token names carry their context — ``@@JS_ID@@`` is JSON-encoded, ``@@XML_ID@@``
is XML-escaped, ``@@HTML_ID@@`` is HTML-escaped — because the same value is
needed in three encodings, and one shared ``@@ID@@`` would put JSON quotes
inside an HTML ``<title>``.
"""

from __future__ import annotations

import json
import re
from html import escape as html_escape
from xml.etree import ElementTree
from xml.sax.saxutils import escape as xml_escape

from .model import Integration
from .paths import native_module_source

__all__ = ["ELECTRON_VERSION", "PLUGIN_FILES", "render_plugin"]

# Electron's version is not something this shell is sensitive to — it only
# needs contextIsolation, which landed in Electron 12. Pinned to the version
# Resolve's own samples ship against so a plugin is reproducible.
ELECTRON_VERSION = "^25.0.0"

#: The files a plugin is made of, in the order they are written.
PLUGIN_FILES: tuple[str, ...] = (
    "manifest.xml",
    "package.json",
    "main.js",
    "preload.js",
    "index.html",
    "js/bridge.js",
    "js/app.js",
    "css/app.css",
)


def _fill(template: str, tokens: dict[str, str]) -> str:
    """Substitute ``@@TOKEN@@`` placeholders, refusing to leave any behind.

    A leftover token would ship as literal text in a file Resolve loads, so it
    is an error rather than something to discover at runtime.
    """
    text = template
    for key, value in tokens.items():
        text = text.replace(f"@@{key}@@", value)
    if "@@" in text:
        raise PluginRenderError(f"unsubstituted token left in template near: {text[:80]!r}")
    return text


class PluginRenderError(Exception):
    """Raised when a plugin template cannot be rendered."""


_MANIFEST = """\
<?xml version="1.0" encoding="UTF-8"?>
<BlackmagicDesign>
    <Plugin>
        <Id>@@XML_ID@@</Id>
        <Name>@@XML_NAME@@</Name>
        <Version>@@XML_VERSION@@</Version>
        <Description>@@XML_DESCRIPTION@@</Description>
        <FilePath>main.js</FilePath>
    </Plugin>
</BlackmagicDesign>
"""

_PACKAGE = """\
{
  "name": "@@SLUG@@",
  "version": @@JSON_VERSION@@,
  "description": @@JSON_DESCRIPTION@@,
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": @@JSON_AUTHOR@@,
  "license": @@JSON_LICENSE@@,
  "devDependencies": {
    "electron": @@JSON_ELECTRON@@
  }
}
"""

_MAIN_JS = """\
// Generated by ResolveScript. Resolve launches this file as the Electron main
// process; manifest.xml next to it is what put this integration in the menu.
//
// Three jobs, in order:
//   1. get the native addon Resolve ships, which is the only bridge to
//      Resolve's JavaScript API and the only source of callbacks;
//   2. register the callbacks this integration declared;
//   3. start the Python integration and answer the renderer from it.
'use strict';

const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');
const { Bridge } = require('./js/bridge.js');

const PLUGIN_ID = @@JS_ID@@;
const PLUGIN_NAME = @@JS_NAME@@;
const CALLBACKS = @@JSON_CALLBACKS@@;
const API_TIMEOUT = @@JS_API_TIMEOUT@@;
const PYTHON = process.env.RESOLVESCRIPT_PYTHON || @@JSON_PYTHON@@;
const SCRIPT = path.join(__dirname, @@JSON_SCRIPT@@);

// Resolve ships WorkflowIntegration.node inside its own installation rather
// than publishing it, so it is copied out of the bundled samples on first run.
function loadNativeAddon() {
    const local = path.join(__dirname, 'WorkflowIntegration.node');
    if (!fs.existsSync(local)) {
        for (const candidate of @@JSON_SEARCH_PATHS@@) {
            if (!fs.existsSync(candidate)) {
                continue;
            }
            try {
                fs.copyFileSync(candidate, local);
                break;
            } catch (err) {
                console.error('Could not copy WorkflowIntegration.node:', err.message);
            }
        }
    }
    if (!fs.existsSync(local)) {
        return null;
    }
    try {
        return require(local);
    } catch (err) {
        console.error('Could not load WorkflowIntegration.node:', err.message);
        return null;
    }
}

// Callbacks are registered against the plugin id, which is why manifest.xml and
// PLUGIN_ID have to agree.
function registerCallbacks() {
    if (!native) {
        return;
    }
    if (API_TIMEOUT > 0) {
        native.SetAPITimeout(API_TIMEOUT);
    }
    for (const name of CALLBACKS) {
        native.RegisterCallback(name, function () {
            // Resolve hands callbacks to JavaScript only, so the Python handler
            // runs as a one-shot subprocess. Its exit code is the outcome.
            const child = spawn(PYTHON, [SCRIPT, '--callback', name], {
                stdio: ['ignore', 'pipe', 'pipe'],
                windowsHide: true
            });
            let out = '';
            child.stdout.on('data', (chunk) => {
                out += chunk;
            });
            child.stderr.on('data', (chunk) =>
                console.error('[' + name + ']', String(chunk).trim())
            );
            child.on('close', (code) => {
                if (code !== 0) {
                    console.error('[' + name + '] failed:', out.trim());
                    return;
                }
                console.log('[' + name + ']', out.trim());
            });
        });
    }
}

function cleanup() {
    if (bridge) {
        bridge.close();
        bridge = null;
    }
    if (native) {
        try {
            native.CleanUp();
        } catch (err) {
            // Resolve is already tearing down; nothing useful to do here.
        }
        native = null;
    }
    resolveApi = null;
}

function createWindow() {
    mainWindow = new BrowserWindow({
        width: @@JS_WIDTH@@,
        height: @@JS_HEIGHT@@,
        minWidth: 320,
        minHeight: 480,
        useContentSize: true,
        title: PLUGIN_NAME,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
            nodeIntegration: false,
            contextIsolation: true
        }
    });
    mainWindow.setMenu(null);
    mainWindow.loadFile(path.join(__dirname, 'index.html'));
    mainWindow.on('closed', () => {
        mainWindow = null;
    });
}

// The renderer has no Node access, so every call it can make is registered here
// and nothing else is reachable.
function registerIpc() {
    const handlers = {
        'workflow:ping': () => ask({ action: 'ping' }),
        'workflow:describe': () => ask({ action: 'describe' }),
        'workflow:context': () => ask({ action: 'context' }),
        'workflow:launch': () => ask({ action: 'launch' }),
        'workflow:callback': (event, name) => ask({ action: 'callback', name: name })
    };
    for (const [channel, handler] of Object.entries(handlers)) {
        ipcMain.handle(channel, handler);
    }
}

function ask(payload) {
    if (!bridge) {
        return { ok: false, error: 'the Python integration is not running' };
    }
    return bridge.request(payload);
}

function report(message) {
    if (mainWindow) {
        return;
    }
    dialog.showErrorBox(PLUGIN_NAME, message);
}

let native = null;
let resolveApi = null;
let bridge = null;
let mainWindow = null;

app.whenReady().then(async () => {
    native = loadNativeAddon();
    if (native) {
        try {
            const initialised = await native.Initialize(PLUGIN_ID);
            if (!initialised) {
                throw new Error('Initialize returned false');
            }
            resolveApi = await native.GetResolve();
            registerCallbacks();
        } catch (err) {
            console.error('Could not connect to Resolve:', err.message);
        }
    } else {
        console.error(
            'WorkflowIntegration.node was not found. The Python integration ' +
            'will still start, but it needs DaVinci Resolve Studio to talk to.'
        );
    }

    if (!fs.existsSync(SCRIPT)) {
        report('Missing ' + SCRIPT + " - run 'resolvescript workflow build'.");
    } else {
        bridge = new Bridge({ python: PYTHON, script: SCRIPT, name: PLUGIN_NAME });
        const started = await bridge.start();
        if (!started.ok) {
            report(
                'Could not start the Python integration:\\n\\n' + started.error +
                '\\n\\nSet RESOLVESCRIPT_PYTHON to a Python 3 interpreter that ' +
                'has ResolveScript installed.'
            );
        }
    }

    registerIpc();
    createWindow();
});

app.on('window-all-closed', () => {
    cleanup();
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (mainWindow === null) {
        createWindow();
    }
});

app.on('before-quit', cleanup);
"""

_PRELOAD_JS = """\
// Generated by ResolveScript. The renderer runs with contextIsolation on, so
// this is the only way it reaches the main process. Every channel here is
// handled in main.js; nothing else is exposed.
'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('workflow', {
    ping: () => ipcRenderer.invoke('workflow:ping'),
    describe: () => ipcRenderer.invoke('workflow:describe'),
    context: () => ipcRenderer.invoke('workflow:context'),
    launch: () => ipcRenderer.invoke('workflow:launch'),
    callback: (name) => ipcRenderer.invoke('workflow:callback', name),
    // Resolve's callbacks are one-way, so a page learns about them by asking
    // rather than by being pushed to.
    on: (event, handler) => {
        const wrapped: (_event, ...args) => handler(...args);
        ipcRenderer.on(event, wrapped);
        return () => ipcRenderer.removeListener(event, wrapped);
    }
});
"""

_BRIDGE_JS = """\
// Generated by ResolveScript. One JSON object per line, in both directions.
// The contract is documented in ResolveScript.workflow.bridge and the Python
// half ships with ResolveScript, so both ends change together.
'use strict';

const { spawn } = require('child_process');

class Bridge {
    constructor({ python, script, name }) {
        this.python = python;
        this.script = script;
        this.name = name;
        this.child = null;
        this.buffer = '';
        this.pending = new Map();
    }

    async start() {
        return new Promise((resolve) => {
            let child;
            try {
                child = spawn(this.python, [this.script, '--serve'], {
                    stdio: ['pipe', 'pipe', 'pipe'],
                    windowsHide: true
                });
            } catch (err) {
                resolve({ ok: false, error: err.message });
                return;
            }
            this.child = child;

            child.stdout.setEncoding('utf8');
            child.stdout.on('data', (chunk) => this.consume(chunk));
            child.stderr.setEncoding('utf8');
            child.stderr.on('data', (chunk) =>
                console.error('[' + this.name + ']', String(chunk).trim())
            );
            child.on('error', (err) => this.fail(err));
            child.on('close', (code) => {
                for (const entry of this.pending.values()) {
                    clearTimeout(entry.timer);
                    entry.resolve({
                        ok: false,
                        error: 'the Python integration exited with code ' + code
                    });
                }
                this.pending.clear();
            });

            // The protocol has no handshake, so ping is how this side learns
            // the interpreter started and imported the integration.
            this.request({ action: 'ping' }).then(resolve);
        });
    }

    consume(chunk) {
        this.buffer += chunk;
        let index = this.buffer.indexOf('\\n');
        while (index !== -1) {
            const line = this.buffer.slice(0, index).trim();
            this.buffer = this.buffer.slice(index + 1);
            if (line) {
                this.dispatch(line);
            }
            index = this.buffer.indexOf('\\n');
        }
    }

    dispatch(line) {
        let message;
        try {
            message = JSON.parse(line);
        } catch (err) {
            console.error('Unparseable message from the integration:', line);
            return;
        }
        const entry = this.pending.get(message.id);
        if (entry === undefined) {
            return;
        }
        this.pending.delete(message.id);
        clearTimeout(entry.timer);
        entry.resolve(message);
    }

    fail(err) {
        for (const entry of this.pending.values()) {
            clearTimeout(entry.timer);
            entry.resolve({ ok: false, error: err.message });
        }
        this.pending.clear();
    }

    request(payload, timeoutMs = 30000) {
        if (this.child === null || this.child.killed) {
            return Promise.resolve({
                ok: false,
                error: 'the Python integration is not running'
            });
        }
        // Replies come back in request order, so they do not need an id echoed
        // from the Python side. The queue below pairs them anyway, which keeps
        // a slow or crashing child from shifting every later reply by one.
        const id = this.pending.size;
        return new Promise((resolve) => {
            const timer = setTimeout(() => {
                this.pending.delete(id);
                resolve({ ok: false, error: 'the integration did not respond' });
            }, timeoutMs);
            this.pending.set(id, { resolve, timer });
            try {
                this.child.stdin.write(JSON.stringify(payload) + '\\n');
            } catch (err) {
                this.pending.delete(id);
                clearTimeout(timer);
                resolve({ ok: false, error: err.message });
            }
        });
    }

    close() {
        if (this.child !== null && !this.child.killed) {
            try {
                this.child.stdin.write(JSON.stringify({ action: 'quit' }) + '\\n');
            } catch (err) {
                // The child is already gone; killing it below is enough.
            }
            this.child.kill();
        }
        this.child = null;
    }
}

module.exports = { Bridge };
"""

_INDEX_HTML = """\
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'none'; style-src 'self'; script-src 'self'">
  <title>@@HTML_NAME@@</title>
  <link rel="stylesheet" href="css/app.css">
</head>
<body>
  <main class="panel">
    <header class="panel__header">
      <h1 class="panel__title">@@HTML_NAME@@</h1>
      <p class="panel__version">@@HTML_VERSION@@ &middot; @@HTML_ID@@</p>
    </header>

    <section class="panel__section">
      <h2 class="panel__heading">Resolve</h2>
      <dl class="facts">
        <dt>Project</dt><dd id="fact-project">&mdash;</dd>
        <dt>Timeline</dt><dd id="fact-timeline">&mdash;</dd>
        <dt>Render jobs</dt><dd id="fact-jobs">&mdash;</dd>
      </dl>
    </section>

    <section class="panel__section" id="callbacks" hidden>
      <h2 class="panel__heading">Callbacks</h2>
      <div class="actions" id="callback-actions"></div>
      <pre class="log" id="callback-log" hidden></pre>
    </section>

    <footer class="panel__footer">
      <button type="button" class="button" id="refresh">Refresh</button>
      <span class="status" id="status">Starting&hellip;</span>
    </footer>
  </main>
  <script src="js/bridge.js"></script>
  <script src="js/app.js"></script>
</body>
</html>
"""

_APP_JS = """\
// Generated by ResolveScript. The page reads the integration's metadata from
// the Python process rather than duplicating it, so the two can never disagree
// about which callbacks exist.
'use strict';

const $ = (id) => document.getElementById(id);
const status = $('status');

function setStatus(text, isError) {
    status.textContent = text;
    status.classList.toggle('status--error', Boolean(isError));
}

function show(node, value) {
    node.textContent =
        value === null || value === undefined || value === '' ? '—' : String(value);
}

async function describe() {
    const reply = await window.workflow.describe();
    if (!reply.ok) {
        setStatus(reply.error, true);
        return null;
    }
    const meta = reply.result;
    document.title = meta.name;
    show(document.querySelector('.panel__title'), meta.name);
    document.querySelector('.panel__version').textContent =
        meta.version + ' · ' + meta.id;

    const section = $('callbacks');
    if (meta.callbacks.length === 0) {
        section.hidden = true;
        return meta;
    }
    section.hidden = false;
    const actions = $('callback-actions');
    actions.replaceChildren();
    for (const name of meta.callbacks) {
        const button = document.createElement('button');
        button.type = 'button';
        button.className = 'button';
        button.textContent = name;
        button.addEventListener('click', () => runCallback(name, button));
        actions.append(button);
    }
    return meta;
}

async function refresh() {
    const reply = await window.workflow.context();
    if (!reply.ok) {
        setStatus(reply.error, true);
        return;
    }
    const info = reply.result;
    show($('fact-project'), info.project);
    show($('fact-timeline'), info.timeline);
    show($('fact-jobs'), info.render_jobs);
    setStatus(info.connected ? 'Connected' : 'Not connected to Resolve', !info.connected);
}

async function runCallback(name, button) {
    button.disabled = true;
    const log = $('callback-log');
    log.hidden = false;
    const reply = await window.workflow.callback(name);
    log.textContent = name + ' -> ' + (reply.ok ? JSON.stringify(reply.result) : reply.error);
    button.disabled = false;
}

$('refresh').addEventListener('click', refresh);

(async function start() {
    if (!window.workflow) {
        setStatus('preload failed - no bridge', true);
        return;
    }
    const ping = await window.workflow.ping();
    if (!ping.ok) {
        setStatus(ping.error, true);
        return;
    }
    await describe();
    await refresh();
})();
"""

_APP_CSS = """\
/* Generated by ResolveScript. The plugin window is a narrow panel, so this is a
   single column with generous line height rather than a layout system. */
:root {
  color-scheme: dark;
  --bg: #16181d;
  --panel: #1e2127;
  --line: #2c3037;
  --text: #e6e8ec;
  --muted: #949aa6;
  --accent: #3b82f6;
  --danger: #ef4444;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 13px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
}

.panel {
  padding: 16px;
  display: grid;
  gap: 16px;
}

.panel__header {
  border-bottom: 1px solid var(--line);
  padding-bottom: 12px;
}

.panel__title {
  margin: 0;
  font-size: 15px;
  font-weight: 600;
}

.panel__version {
  margin: 2px 0 0;
  color: var(--muted);
  font-size: 11px;
}

.panel__section {
  display: grid;
  gap: 8px;
}

.panel__heading {
  margin: 0;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--muted);
}

.panel__footer {
  display: flex;
  align-items: center;
  gap: 10px;
  border-top: 1px solid var(--line);
  padding-top: 12px;
}

.facts {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 4px 12px;
  margin: 0;
}

.facts dt {
  color: var(--muted);
}

.facts dd {
  margin: 0;
  overflow-wrap: anywhere;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.button {
  border: 1px solid var(--line);
  border-radius: 6px;
  background: var(--panel);
  color: var(--text);
  padding: 6px 12px;
  font: inherit;
  cursor: pointer;
}

.button:hover:not(:disabled) {
  border-color: var(--accent);
}

.button:disabled {
  opacity: 0.5;
  cursor: default;
}

.status {
  color: var(--muted);
  font-size: 11px;
}

.status--error {
  color: var(--danger);
}

.log {
  margin: 0;
  padding: 8px;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 6px;
  font: 11px/1.4 ui-monospace, "Cascadia Code", Consolas, monospace;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  max-height: 160px;
  overflow: auto;
}
"""


def render_plugin(
    integration: Integration,
    *,
    script_rel: str = "",
    width: int = 420,
    height: int = 620,
    search_paths: list[str] | None = None,
) -> dict[str, str]:
    """Return the plugin's files as ``{relative path: source}``.

    Pure — nothing is written; :mod:`ResolveScript.workflow.build` does that.

    :param script_rel: where the generated Python launcher sits, relative to
        the plugin directory. Defaults to the launcher in the parent, which is
        where :func:`~ResolveScript.workflow.build.build` puts it.
    :param width: the window's width in pixels.
    :param height: the window's height in pixels.
    :param search_paths: full paths to look for ``WorkflowIntegration.node`` in;
        defaults to the copies inside Resolve's bundled sample plugins.
    """
    if search_paths is None:
        search_paths = [str(path) for path in native_module_source()]

    description = integration.description or integration.name
    slug = integration.id.replace(".", "-")
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", slug):
        # npm rejects these, and a plugin whose package.json is not installable
        # fails long after Resolve has already found it.
        raise PluginRenderError(
            f"integration id {integration.id!r} does not produce a usable npm "
            f"package name ({slug!r}); use lowercase letters, digits and dots"
        )

    tokens = {
        # JSON encoding — for values interpolated into JavaScript source and
        # into package.json, where they must be valid JSON values.
        "JSON_ID": json.dumps(integration.id),
        "JSON_NAME": json.dumps(integration.name),
        "JSON_VERSION": json.dumps(integration.version),
        "JSON_DESCRIPTION": json.dumps(description),
        "JSON_AUTHOR": json.dumps(integration.author or "ResolveScript"),
        "JSON_LICENSE": json.dumps(integration.license),
        "JSON_ELECTRON": json.dumps(ELECTRON_VERSION),
        "JSON_CALLBACKS": json.dumps(sorted(integration.callbacks)),
        "JSON_PYTHON": json.dumps(integration.python),
        "JSON_SCRIPT": json.dumps(script_rel or f"../{integration.script_name}"),
        "JSON_SEARCH_PATHS": json.dumps(search_paths),
        # Bare JavaScript — numbers and already-quoted strings.
        "JS_ID": json.dumps(integration.id),
        "JS_NAME": json.dumps(integration.name),
        "JS_API_TIMEOUT": str(int(integration.api_timeout)),
        "JS_WIDTH": str(int(width)),
        "JS_HEIGHT": str(int(height)),
        # Markup escaping — text content, so no surrounding quotes.
        "XML_ID": xml_escape(integration.id),
        "XML_NAME": xml_escape(integration.name),
        "XML_VERSION": xml_escape(integration.version),
        "XML_DESCRIPTION": xml_escape(description),
        "HTML_NAME": html_escape(integration.name),
        "HTML_VERSION": html_escape(integration.version),
        "HTML_ID": html_escape(integration.id),
        "SLUG": slug,
    }

    files = {
        "manifest.xml": _fill(_MANIFEST, tokens),
        "package.json": _fill(_PACKAGE, tokens),
        "main.js": _fill(_MAIN_JS, tokens),
        "preload.js": _PRELOAD_JS,
        "index.html": _fill(_INDEX_HTML, tokens),
        "js/bridge.js": _BRIDGE_JS,
        "js/app.js": _APP_JS,
        "css/app.css": _APP_CSS,
    }
    _verify(files)
    return files


def _verify(files: dict[str, str]) -> None:
    """Fail loudly on the two files a mistake in them would hide.

    A package.json that is not valid JSON still installs — npm is never run by
    Resolve — so the only signal is the plugin failing to launch much later,
    with nothing pointing at the cause. Checking it here costs nothing.
    """
    try:
        json.loads(files["package.json"])
    except ValueError as exc:
        raise PluginRenderError(f"generated package.json is not valid JSON: {exc}") from exc
    try:
        ElementTree.fromstring(files["manifest.xml"])
    except ElementTree.ParseError as exc:
        raise PluginRenderError(f"generated manifest.xml is not valid XML: {exc}") from exc
