"""Generating the Python launcher Resolve executes.

This is the portable artifact. Drop the generated file into the Workflow
Integration Plugins root and Resolve lists it under
``Workspace > Workflow Integrations``; choosing it runs the file with ``resolve``
and ``project`` already bound as globals, and the file shows whatever window
:mod:`ResolveScript.ui` builds.

The generated module is a build artifact, not source. It is a pure function of
the :class:`~ResolveScript.workflow.model.Integration` plus a few build
options, so it is regenerated rather than edited — which is why it imports your
integration by name instead of inlining it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from string import Template

from .model import Integration, WorkflowError

__all__ = ["ScriptOptions", "render_script"]

_DOTTED_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$")

_TEMPLATE = Template(
    '''"""$name — DaVinci Resolve Workflow Integration.

$description

Generated by ResolveScript from `$module.$attribute`. Edit the Integration and
re-run `resolvescript workflow build`; this file is overwritten.
"""

from __future__ import annotations

import os
import sys

# Resolve launches a Workflow Integration script from the plugins root, which
# knows nothing about this project's layout, so put the project back on the
# path. It only has to be right for the machine that runs this file, which is
# why it is baked in at build time rather than discovered at runtime.
_PROJECT_ROOT = r"$project_root"
if _PROJECT_ROOT and os.path.isdir(_PROJECT_ROOT) and _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# Resolve binds `resolve` and `project` as globals when it launches a Workflow
# Integration script. Reading them through globals() keeps this file importable
# outside Resolve, where they do not exist and script_main() discovers Resolve
# the ordinary way.
resolve = globals().get("resolve")
project = globals().get("project")

from ResolveScript.workflow import main as _main  # noqa: E402

from $module import $attribute as INTEGRATION  # noqa: E402


if __name__ == "__main__":
    raise SystemExit(_main(INTEGRATION, resolve=resolve, project=project))
'''
)


@dataclass
class ScriptOptions:
    """Where the integration lives, for the generated import.

    :param module: the dotted path of the module holding the integration.
    :param attribute: the name it is bound to there.
    :param project_root: the directory to prepend to ``sys.path``; defaults to
        the directory containing the module's top-level package.
    """

    module: str = ""
    attribute: str = "INTEGRATION"
    project_root: str = ""

    def __post_init__(self) -> None:
        if self.module and not _DOTTED_RE.match(self.module):
            raise WorkflowError(
                f"module {self.module!r} is not a dotted Python path, e.g. 'my_pkg.integration'"
            )
        if not _DOTTED_RE.match(self.attribute):
            raise WorkflowError(f"attribute {self.attribute!r} is not a Python identifier")
        self.project_root = str(Path(self.project_root).resolve()) if self.project_root else ""


def render_script(integration: Integration, options: ScriptOptions | None = None) -> str:
    """Return the source of the launcher for ``integration``.

    The result is a complete, importable module, and the only thing it needs
    from the project is the dotted path the integration is defined at::

        source = render_script(
            Integration(name="Deliver", id="com.acme.deliver"),
            ScriptOptions("my_pkg.integration", project_root=".."),
        )
    """
    if not integration.name:
        raise WorkflowError("an integration needs a name")
    opts = options or ScriptOptions()
    if not opts.module:
        raise WorkflowError(
            "the generated launcher imports the integration by name, so it needs "
            "module= (the dotted path it is defined in)"
        )
    description = integration.description.strip() or f"{integration.name} workflow integration."
    return _TEMPLATE.substitute(
        name=integration.name,
        description=description,
        module=opts.module,
        attribute=opts.attribute,
        project_root=opts.project_root,
    )
