"""Rendering a :class:`~ResolveScript.fuse.Fuse` into one ``.fuse`` file.

The output is deliberately plain Lua in the style of Blackmagic's own
``Null.Fuse``: tab-indented, a comment header, and nothing clever. A fuse is
read and edited by hand more often than any other artifact this tool produces,
and it is loaded by the Fusion page rather than by Resolve's Python host, so
there is no interpreter here to hide behind.

Substitution is ``@@TOKEN@@`` replacement, never ``str.format``. The generated
file is full of braces — every ``AddInput`` takes a table — and a format string
would make the output depend on escaping a brace the author happened not to
notice. :func:`_fill` is the only place a template is interpolated, and it
refuses to ship a file with a token left in it.

The one value that is *not* token-substituted is the author's ``process`` body.
It is Lua they wrote, spliced in verbatim: a long-bracket string inside it — the
usual way to run a pixel expression — must not be touched, and a stray ``@@``
in a comment must not be mistaken for a placeholder.
"""

from __future__ import annotations

import re
import textwrap

from .model import Control, Fuse, FuseError, Output, _lua_value

__all__ = ["FUSE_EXTENSION", "NO_MASK_FLAG", "REGISTER_FLAGS", "render_fuse"]

#: The extension Fusion gives a scripted plugin. Case does not matter to it, but
#: lower case is what the SDK and the manual use.
FUSE_EXTENSION = ".fuse"

#: The controls Fusion adds to every ``CT_Tool`` unless told not to: a blend
#: control, and object/material and motion-blur controls. A fuse that does its
#: own compositing wants none of them, and each one it keeps is a row in the
#: Inspector that does nothing. ``REG_OpNoMask`` is separate because a
#: ``CT_SourceTool`` replaces the chain and must keep its mask.
REGISTER_FLAGS: tuple[str, ...] = (
    "REG_NoBlendCtrls",
    "REG_NoObjMatCtrls",
    "REG_NoMotionBlurCtrls",
)

#: The mask input, suppressed for every tool except a source.
NO_MASK_FLAG = "REG_OpNoMask"

_HEADER = """\
--[[--
@@NAME@@ @@VERSION@@
@@DESCRIPTION@@

Generated by ResolveScript from a Fuse declaration. This file is the
deliverable: Fusion loads it directly, and editing it here is fine. Just
rebuild from the declaration to pick up your changes again.

@@META@@
--]]--
"""

_REGISTER = """
FuRegisterClass(@@LUA_CLASS_NAME@@, @@TOOL_CLASS@@, {
@@REGISTER_BODY@@	})
"""

_CREATE = """

function Create()"""

_PROCESS = """

function Process(req)
@@PROCESS@@end
"""

#: A ``@@TOKEN@@`` placeholder, as opposed to an ``@@`` that is just text.
_PLACEHOLDER = re.compile(r"@@([A-Z0-9_]+)@@")

#: A Lua long-bracket string, including the *leveled* form ``[=[ ... ]=]`` that
#: pixel expressions are usually written in. A line that *starts* inside one of
#: these must not be indented: the expression is the string, and its leading
#: whitespace would become part of the code Fusion compiles.
_LONG_BRACKET = re.compile(r"\[(=*)\[.*?\]\1\]", re.DOTALL)


def _fill(template: str, tokens: dict[str, str]) -> str:
    """Substitute ``@@TOKEN@@`` placeholders, refusing to leave any behind.

    A leftover token would ship as literal text in a file Fusion loads, so it is
    an error here rather than something to find in the registry menu.

    The check runs against the *template*, before any value goes in. Checking
    afterwards would also reject a description that happens to contain ``@@``,
    which is a real string a real tool could have, and would report it as a
    template bug it is not.
    """
    if leftover := _PLACEHOLDER.findall(template):
        missing = [token for token in leftover if token.strip("@") not in tokens]
        if missing:
            raise FuseError(
                f"fuse template has no value for {', '.join(sorted(set(missing)))}"
            )
    text = template
    for key, value in tokens.items():
        text = text.replace(f"@@{key}@@", value)
    return text


def _byline(label: str, value: str) -> str:
    return f"{label}: {value}" if value else ""


def _header(fuse: Fuse) -> str:
    """The ``--[[-- ... --]]--`` comment."""
    details = [
        _byline("tool class", fuse.tool_type),
        _byline("class", fuse.class_name),
        _byline("category", fuse.category),
        _byline("icon", fuse.icon_string),
        _byline("author", fuse.author),
        _byline("license", fuse.license),
    ]
    return _fill(
        _HEADER,
        {
            "NAME": fuse.name,
            "VERSION": fuse.version,
            "DESCRIPTION": fuse.description or "(no description)",
            "META": "\n".join(line for line in details if line),
        },
    )


def _register(fuse: Fuse) -> str:
    """The ``FuRegisterClass`` call, in a stable order with the author's last."""
    entries: list[tuple[str, str]] = [
        ("REGS_Name", _lua_value(fuse.name)),
        ("REGS_Category", _lua_value(fuse.category)),
        ("REGS_OpIconString", _lua_value(fuse.icon_string)),
        ("REGS_OpDescription", _lua_value(fuse.description or fuse.name)),
    ]
    flags = list(REGISTER_FLAGS)
    if not fuse.is_source:
        flags.insert(0, NO_MASK_FLAG)
    for key in flags:
        entries.append((key, "true"))
    for key, value in fuse.flags.items():
        entries.append((key, _lua_value(value)))
    body = "".join(f"\t{key} = {value},\n" for key, value in entries)
    return _fill(
        _REGISTER,
        {
            "LUA_CLASS_NAME": _lua_value(fuse.class_name),
            "TOOL_CLASS": fuse.tool_type,
            "REGISTER_BODY": body,
        },
    )


def _input(port: Control) -> str:
    properties = "".join(
        f"\t\t{key} = {value},\n" for key, value in port.properties().items()
    )
    return (
        f"\n\t{port.variable} = self:AddInput({_lua_value(port.label)}, "
        f"{_lua_value(port.id)}, {{\n{properties}\t\t}})\n"
    )


def _output(port: Output) -> str:
    properties = "".join(
        f"\t\t{key} = {value},\n" for key, value in port.properties().items()
    )
    return (
        f"\n\t{port.variable} = self:AddOutput({_lua_value(port.label)}, "
        f"{_lua_value(port.id)}, {{\n{properties}\t\t}})\n"
    )


def _create(fuse: Fuse) -> str:
    body = "".join(_input(port) for port in fuse.inputs)
    body += "".join(_output(port) for port in fuse.outputs)
    extra = textwrap.dedent(fuse.create).strip("\n")
    if extra:
        # Author-supplied declarations land last so they can override or add to
        # what the Fuse dataclass generated.
        body += "\n" + textwrap.indent(extra, "\t").rstrip() + "\n"
    return _CREATE + body + "end\n"


def _protected_lines(body: str) -> set[int]:
    """Zero-based line numbers that sit inside a ``[[ ... ]]`` block.

    Those lines carry string content, so their leading whitespace is data and
    must survive re-indentation untouched.
    """
    lines: set[int] = set()
    for match in _LONG_BRACKET.finditer(body):
        start = body.count("\n", 0, match.start())
        end = body.count("\n", 0, match.end())
        lines.update(range(start + 1, end + 1))
    return lines


def _process(fuse: Fuse) -> str:
    """The ``Process`` function.

    The body is dedented and re-indented one level so it lines up with the rest
    of the file, but *not* inside a long-bracket block: a ``DoExpression`` is
    the normal way to write pixel work in a fuse, and indenting within ``[[ ]]
    would silently change the expression Fusion runs.
    """
    body = textwrap.dedent(fuse.process).strip("\n")
    protected = _protected_lines(body)
    indented = [
        line if not line.strip() or index in protected else f"\t{line}"
        for index, line in enumerate(body.splitlines())
    ]
    return _fill(_PROCESS, {"PROCESS": "\n".join(indented) + "\n"})


def render_fuse(fuse: Fuse) -> str:
    """Return the complete ``.fuse`` source for ``fuse``.

    Pure — nothing is written, and nothing is compiled. Fusion compiles the file
    when it builds its registry, which is exactly why a structural or parse
    problem is invisible until then; :mod:`ResolveScript.fuse.validate` is where
    that gets caught instead.
    """
    text = _header(fuse) + _register(fuse) + _create(fuse) + _process(fuse)
    if not text.endswith("\n"):
        text += "\n"
    return text
